services:
  web:
    build: .
    container_name: node-js
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      PORT : "3000" 
    depends_on:
      db:
        condition: service_healthy
      
    command: npm run dev

  db:
    image:  mongo:7.0
    container_name: mongo-db
    restart: unless-stopped
    ports:
      - "27017:27017"
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "mongosh --username $MONGO_INITDB_ROOT_USERNAME --password $MONGO_INITDB_ROOT_PASSWORD --authenticationDatabase admin --eval \"db.adminCommand('ping')\""]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    volumes:
      - mongo_data:/data/db

volumes:
   mongo_data:

