FROM alpine:3.19 AS builder 

WORKDIR /app

COPY . .

FROM nginx:1.25-alpine

COPY --from=builder /app /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

